export const SHOW_MAP_MODAL = "SHOW_MAP_MODAL"

export const GET_CURRENT_LOCATION = "GET_CURRRENT_LOCATION"
export const GET_CURRENT_LOCATION_ERROR = "GET_CURRRENT_LOCATION_ERROR"

export const GET_LOCATION_FOR_FORM = "GET_LOCATION_FOR_FORM"